const fs = require('fs-extra')
if (fs.existsSync('.env')) require('dotenv').config({ path: __dirname+'/.env' })


//═══════[Required Variables]════════\\
global.audio= "" ;  
global.video= "" ;
global.port =process.env.PORT
global.appUrl=process.env.APP_URL ||"postgresql://suhail_databas_user:4EMhqdBFLB5sVlrMBqdrEU9E7XHOvnuf@dpg-cqq6o5ogph6c7385lpp0-a/suhail_databas"                       // put your app url here,
global.email ="saimsamsun789@gmail.com"
global.location="Lahore,Pakistan."


global.mongodb= process.env.MONGODB_URI || ""
global.allowJids= process.env.ALLOW_JID || "null" 
global.blockJids= process.env.BLOCK_JID || "null"
global.DATABASE_URL = process.env.DATABASE_URL || ""

global.timezone= process.env.TZ || process.env.TIME_ZONE || "Asia/Karachi";
global.github=process.env.GITHUB|| "https://github.com/SuhailTechInfo/Suhail-Md";
global.gurl  =process.env.GURL  || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643";
global.website=process.env.GURL || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643" ; 
global.THUMB_IMAGE = process.env.THUMB_IMAGE || process.env.IMAGE || "https://github.com/SuhailTechInfo/Suhail-Md/blob/main/lib/assets/suhail.jpg?raw=true" ; // SET LOGO FOR IMAGE 
global.caption = process.env.CAPTION || global.caption || "ᴘᴏᴡᴇʀᴇᴅ ʙʏ sᴜʜᴀɪʟ²²¹-ᴍᴅ" 


global.devs = "237679672107" // Developer Contact
global.sudo = process.env.SUDO ? process.env.SUDO.replace(/[\s+]/g, '') : "null";
global.owner= process.env.OWNER_NUMBER ? process.env.OWNER_NUMBER.replace(/[\s+]/g, '') : "923184474176";




//========================= [ BOT SETTINGS ] ======8===================\\
global.style = process.env.STYLE   || Math.floor(Math.random()*6) || '0'  // put '1' to "5" here to check bot styles
global.flush = process.env.FLUSH   || "false"; // Make it "true" if bot not responed
global.gdbye = process.env.GOODBYE || process.env.CAN_GOODBYE || "true"; 
global.wlcm  = process.env.WELCOME || process.env.CAN_WELCOME || "true";  // Make it "false" for disable WELCOME 

global.warncount = process.env.WARN_COUNT || 3
global.disablepm = process.env.DISABLE_PM || "false"
global.disablegroup = process.env.DISABLE_GROUPS || "false", // disable bot in groups when public mode

global.MsgsInLog = process.env.MSGS_IN_LOG|| "true" // "true"  to see messages , "log" to show logs , "false" to hide logs messages
global.userImages= process.env.USER_IMAGES || "text" // "text" // set Image/video urls here
global.waPresence= process.env.WAPRESENCE ||  "null" ; // 'unavailable' | 'available' | 'composing' | 'recording' | 'paused'


//========================= [ AUTO READ MSGS & CMDS ] =========================\\
global.readcmds = process.env.READ_COMMAND || "true"
global.readmessage = process.env.READ_MESSAGE || "false"
global.readmessagefrom = process.env.READ_MESSAGE_FROM || "null,923xxxxxxxx";


//========================= [ AUTO SAVE & READ STATUS ] =========================\\
global.read_status = process.env.AUTO_READ_STATUS || "true"
global.save_status = process.env.AUTO_SAVE_STATUS || "false"
global.save_status_from =  process.env.SAVE_STATUS_FROM  || "null,923xxxxxxxx";
global.read_status_from =  process.env.READ_STATUS_FROM  ||  "923184474176,923xxxxxxxx";

global.api_smd = "https://api-smd.onrender.com" //  || "https://api-smd-1.vercel.app" // expires
global.scan = "https://suhail-md-vtsf.onrender.com";


global.SESSION_ID = "SUHAIL_12_22_07_22_ewogICJjcmVkcy5qc29uIjogIntcbiAgXCJub2lzZUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTkyLFxuICAgICAgICAyLFxuICAgICAgICA1OSxcbiAgICAgICAgMjIwLFxuICAgICAgICAxMyxcbiAgICAgICAgNDEsXG4gICAgICAgIDI0OCxcbiAgICAgICAgMjM0LFxuICAgICAgICAxMCxcbiAgICAgICAgMjcsXG4gICAgICAgIDE5NixcbiAgICAgICAgMjQxLFxuICAgICAgICA2LFxuICAgICAgICAxMDksXG4gICAgICAgIDkzLFxuICAgICAgICAyMDgsXG4gICAgICAgIDE2NixcbiAgICAgICAgMTc4LFxuICAgICAgICAyMjEsXG4gICAgICAgIDIxOSxcbiAgICAgICAgMjEyLFxuICAgICAgICAyNDcsXG4gICAgICAgIDE0OSxcbiAgICAgICAgMjU1LFxuICAgICAgICAyNTMsXG4gICAgICAgIDQ2LFxuICAgICAgICA1MyxcbiAgICAgICAgMjA5LFxuICAgICAgICA4LFxuICAgICAgICAxNjAsXG4gICAgICAgIDEzMixcbiAgICAgICAgMTE4XG4gICAgICBdXG4gICAgfSxcbiAgICBcInB1YmxpY1wiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDc0LFxuICAgICAgICAxMzYsXG4gICAgICAgIDE0OSxcbiAgICAgICAgMjUyLFxuICAgICAgICAyMDEsXG4gICAgICAgIDE3MSxcbiAgICAgICAgMTkyLFxuICAgICAgICAxOSxcbiAgICAgICAgMTIsXG4gICAgICAgIDQwLFxuICAgICAgICA0NSxcbiAgICAgICAgMTQ1LFxuICAgICAgICAyMzAsXG4gICAgICAgIDM0LFxuICAgICAgICA0MyxcbiAgICAgICAgMTgzLFxuICAgICAgICAxNDgsXG4gICAgICAgIDQxLFxuICAgICAgICA1MCxcbiAgICAgICAgMTcsXG4gICAgICAgIDE2OSxcbiAgICAgICAgMjQ3LFxuICAgICAgICAxODcsXG4gICAgICAgIDIzNyxcbiAgICAgICAgMTY1LFxuICAgICAgICAxNDksXG4gICAgICAgIDE1MyxcbiAgICAgICAgMTE0LFxuICAgICAgICAxNjAsXG4gICAgICAgIDExNCxcbiAgICAgICAgMTA0LFxuICAgICAgICA3OFxuICAgICAgXVxuICAgIH1cbiAgfSxcbiAgXCJwYWlyaW5nRXBoZW1lcmFsS2V5UGFpclwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMjQ4LFxuICAgICAgICAzOCxcbiAgICAgICAgOTcsXG4gICAgICAgIDE0NyxcbiAgICAgICAgNDIsXG4gICAgICAgIDE2MixcbiAgICAgICAgNzUsXG4gICAgICAgIDgzLFxuICAgICAgICAxNTMsXG4gICAgICAgIDEzOCxcbiAgICAgICAgMTgyLFxuICAgICAgICAxNjMsXG4gICAgICAgIDQ1LFxuICAgICAgICAxODIsXG4gICAgICAgIDEyMCxcbiAgICAgICAgMjQ2LFxuICAgICAgICAyMTgsXG4gICAgICAgIDE4MyxcbiAgICAgICAgMTU1LFxuICAgICAgICAyNTMsXG4gICAgICAgIDE0OSxcbiAgICAgICAgMTQsXG4gICAgICAgIDI0NixcbiAgICAgICAgMTUsXG4gICAgICAgIDExMSxcbiAgICAgICAgMjUzLFxuICAgICAgICAyNDEsXG4gICAgICAgIDExNCxcbiAgICAgICAgMTYyLFxuICAgICAgICA2LFxuICAgICAgICAyMzgsXG4gICAgICAgIDY3XG4gICAgICBdXG4gICAgfSxcbiAgICBcInB1YmxpY1wiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDI0MyxcbiAgICAgICAgNzUsXG4gICAgICAgIDY2LFxuICAgICAgICAyMTYsXG4gICAgICAgIDE0NixcbiAgICAgICAgMTY1LFxuICAgICAgICAyNDMsXG4gICAgICAgIDI2LFxuICAgICAgICAyNDIsXG4gICAgICAgIDY5LFxuICAgICAgICA2NCxcbiAgICAgICAgMTE0LFxuICAgICAgICAxNzksXG4gICAgICAgIDE2NCxcbiAgICAgICAgNSxcbiAgICAgICAgNTgsXG4gICAgICAgIDEsXG4gICAgICAgIDExMSxcbiAgICAgICAgMSxcbiAgICAgICAgMTgyLFxuICAgICAgICA3OSxcbiAgICAgICAgMTU4LFxuICAgICAgICAxNTEsXG4gICAgICAgIDk4LFxuICAgICAgICAyMTIsXG4gICAgICAgIDQ1LFxuICAgICAgICAxODksXG4gICAgICAgIDY4LFxuICAgICAgICAxMjQsXG4gICAgICAgIDE3MixcbiAgICAgICAgMTY5LFxuICAgICAgICAxMDRcbiAgICAgIF1cbiAgICB9XG4gIH0sXG4gIFwic2lnbmVkSWRlbnRpdHlLZXlcIjoge1xuICAgIFwicHJpdmF0ZVwiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDcyLFxuICAgICAgICA1OSxcbiAgICAgICAgMSxcbiAgICAgICAgNTMsXG4gICAgICAgIDE0NixcbiAgICAgICAgMjEwLFxuICAgICAgICA3OSxcbiAgICAgICAgOCxcbiAgICAgICAgMTQ5LFxuICAgICAgICAyMzgsXG4gICAgICAgIDE5NyxcbiAgICAgICAgMjM2LFxuICAgICAgICA4NixcbiAgICAgICAgMTY2LFxuICAgICAgICAxMzcsXG4gICAgICAgIDE3OSxcbiAgICAgICAgMjU0LFxuICAgICAgICAzMSxcbiAgICAgICAgNDAsXG4gICAgICAgIDExMSxcbiAgICAgICAgMTQ5LFxuICAgICAgICAyMDQsXG4gICAgICAgIDg5LFxuICAgICAgICAyNTEsXG4gICAgICAgIDMyLFxuICAgICAgICA2OCxcbiAgICAgICAgMjMsXG4gICAgICAgIDE1NCxcbiAgICAgICAgMjM0LFxuICAgICAgICAyNTUsXG4gICAgICAgIDEwNyxcbiAgICAgICAgNjRcbiAgICAgIF1cbiAgICB9LFxuICAgIFwicHVibGljXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTQ2LFxuICAgICAgICAxOTMsXG4gICAgICAgIDEzMixcbiAgICAgICAgNjgsXG4gICAgICAgIDIxNixcbiAgICAgICAgMjI1LFxuICAgICAgICAxODMsXG4gICAgICAgIDEyMixcbiAgICAgICAgNSxcbiAgICAgICAgNjAsXG4gICAgICAgIDE1MixcbiAgICAgICAgMTU1LFxuICAgICAgICAzMyxcbiAgICAgICAgMjAwLFxuICAgICAgICAyNDUsXG4gICAgICAgIDE4OCxcbiAgICAgICAgMTQ0LFxuICAgICAgICAxMTIsXG4gICAgICAgIDExNyxcbiAgICAgICAgMTQ1LFxuICAgICAgICAyMTUsXG4gICAgICAgIDYsXG4gICAgICAgIDIzMixcbiAgICAgICAgMjI5LFxuICAgICAgICA2NyxcbiAgICAgICAgNjYsXG4gICAgICAgIDYzLFxuICAgICAgICAwLFxuICAgICAgICAxOTYsXG4gICAgICAgIDE4OSxcbiAgICAgICAgMTc5LFxuICAgICAgICAyN1xuICAgICAgXVxuICAgIH1cbiAgfSxcbiAgXCJzaWduZWRQcmVLZXlcIjoge1xuICAgIFwia2V5UGFpclwiOiB7XG4gICAgICBcInByaXZhdGVcIjoge1xuICAgICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgICAyNDAsXG4gICAgICAgICAgNyxcbiAgICAgICAgICA0MSxcbiAgICAgICAgICA0NSxcbiAgICAgICAgICAxNDQsXG4gICAgICAgICAgMjMyLFxuICAgICAgICAgIDU4LFxuICAgICAgICAgIDM5LFxuICAgICAgICAgIDk3LFxuICAgICAgICAgIDMwLFxuICAgICAgICAgIDE1NCxcbiAgICAgICAgICAyMTAsXG4gICAgICAgICAgMTIyLFxuICAgICAgICAgIDU2LFxuICAgICAgICAgIDI0LFxuICAgICAgICAgIDM5LFxuICAgICAgICAgIDExNyxcbiAgICAgICAgICAxOTgsXG4gICAgICAgICAgNzksXG4gICAgICAgICAgNjQsXG4gICAgICAgICAgMTI0LFxuICAgICAgICAgIDE0NyxcbiAgICAgICAgICAxMzksXG4gICAgICAgICAgMTAzLFxuICAgICAgICAgIDI2LFxuICAgICAgICAgIDE0MixcbiAgICAgICAgICAxNjAsXG4gICAgICAgICAgMjIyLFxuICAgICAgICAgIDk5LFxuICAgICAgICAgIDE2MixcbiAgICAgICAgICAyNTAsXG4gICAgICAgICAgOTdcbiAgICAgICAgXVxuICAgICAgfSxcbiAgICAgIFwicHVibGljXCI6IHtcbiAgICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgICAgMjUsXG4gICAgICAgICAgMjI2LFxuICAgICAgICAgIDE4LFxuICAgICAgICAgIDEwNSxcbiAgICAgICAgICAyLFxuICAgICAgICAgIDIxNCxcbiAgICAgICAgICAxMTMsXG4gICAgICAgICAgMTQwLFxuICAgICAgICAgIDMzLFxuICAgICAgICAgIDM4LFxuICAgICAgICAgIDk3LFxuICAgICAgICAgIDI0NSxcbiAgICAgICAgICAyMzEsXG4gICAgICAgICAgMTEzLFxuICAgICAgICAgIDE1MCxcbiAgICAgICAgICA4MixcbiAgICAgICAgICA2NixcbiAgICAgICAgICAxNCxcbiAgICAgICAgICAyNDEsXG4gICAgICAgICAgMTY5LFxuICAgICAgICAgIDUsXG4gICAgICAgICAgNjEsXG4gICAgICAgICAgODUsXG4gICAgICAgICAgMjIwLFxuICAgICAgICAgIDk5LFxuICAgICAgICAgIDcxLFxuICAgICAgICAgIDIwNyxcbiAgICAgICAgICAyMTksXG4gICAgICAgICAgMjQ1LFxuICAgICAgICAgIDIyMyxcbiAgICAgICAgICAzMSxcbiAgICAgICAgICAxNlxuICAgICAgICBdXG4gICAgICB9XG4gICAgfSxcbiAgICBcInNpZ25hdHVyZVwiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDE1NixcbiAgICAgICAgMTMsXG4gICAgICAgIDI1MyxcbiAgICAgICAgNjUsXG4gICAgICAgIDIwMyxcbiAgICAgICAgMTM0LFxuICAgICAgICAyMDMsXG4gICAgICAgIDEsXG4gICAgICAgIDE4MixcbiAgICAgICAgNDcsXG4gICAgICAgIDE2NixcbiAgICAgICAgMzcsXG4gICAgICAgIDIwMSxcbiAgICAgICAgNyxcbiAgICAgICAgMjMwLFxuICAgICAgICA0NixcbiAgICAgICAgMTU3LFxuICAgICAgICAxNjUsXG4gICAgICAgIDE3MixcbiAgICAgICAgMTE4LFxuICAgICAgICA2MyxcbiAgICAgICAgMjQ0LFxuICAgICAgICAyMjMsXG4gICAgICAgIDIwOSxcbiAgICAgICAgMjQxLFxuICAgICAgICAxOTcsXG4gICAgICAgIDEyLFxuICAgICAgICAyMTMsXG4gICAgICAgIDQ3LFxuICAgICAgICAxNDEsXG4gICAgICAgIDE1OCxcbiAgICAgICAgNjMsXG4gICAgICAgIDIxOSxcbiAgICAgICAgMTg0LFxuICAgICAgICAyMjEsXG4gICAgICAgIDExLFxuICAgICAgICAyMzAsXG4gICAgICAgIDQyLFxuICAgICAgICAyNTEsXG4gICAgICAgIDY5LFxuICAgICAgICAxNDQsXG4gICAgICAgIDE2OSxcbiAgICAgICAgNzksXG4gICAgICAgIDExOSxcbiAgICAgICAgMjI1LFxuICAgICAgICAxNzUsXG4gICAgICAgIDEyNCxcbiAgICAgICAgMjM4LFxuICAgICAgICAyNDYsXG4gICAgICAgIDIxNCxcbiAgICAgICAgODUsXG4gICAgICAgIDE5NixcbiAgICAgICAgMTU1LFxuICAgICAgICAyMDMsXG4gICAgICAgIDEzMCxcbiAgICAgICAgMTcsXG4gICAgICAgIDExNyxcbiAgICAgICAgMTg3LFxuICAgICAgICAxMjgsXG4gICAgICAgIDgwLFxuICAgICAgICAyNDksXG4gICAgICAgIDE1OSxcbiAgICAgICAgMTcxLFxuICAgICAgICAxNDBcbiAgICAgIF1cbiAgICB9LFxuICAgIFwia2V5SWRcIjogMVxuICB9LFxuICBcInJlZ2lzdHJhdGlvbklkXCI6IDIzNixcbiAgXCJhZHZTZWNyZXRLZXlcIjogXCJXOEJPaEFieGl4YU92elVkWDFmc3k1RnVsejM3SXkvU3duZWpFYndhSUFJPVwiLFxuICBcInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlc1wiOiBbXSxcbiAgXCJuZXh0UHJlS2V5SWRcIjogMzEsXG4gIFwiZmlyc3RVbnVwbG9hZGVkUHJlS2V5SWRcIjogMzEsXG4gIFwiYWNjb3VudFN5bmNDb3VudGVyXCI6IDAsXG4gIFwiYWNjb3VudFNldHRpbmdzXCI6IHtcbiAgICBcInVuYXJjaGl2ZUNoYXRzXCI6IGZhbHNlXG4gIH0sXG4gIFwiZGV2aWNlSWRcIjogXCJxY0xzQzJWM1JidTFKNnVFeEtoSlFBXCIsXG4gIFwicGhvbmVJZFwiOiBcIjI5MTkzY2Q2LWIzMjEtNDdhYi1hNTBiLTUxM2NhMzgwNzk3MVwiLFxuICBcImlkZW50aXR5SWRcIjoge1xuICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgIFwiZGF0YVwiOiBbXG4gICAgICAyMDcsXG4gICAgICAyNTMsXG4gICAgICAxLFxuICAgICAgNjIsXG4gICAgICAxMjgsXG4gICAgICAxMjgsXG4gICAgICAyMzgsXG4gICAgICAzMCxcbiAgICAgIDE1MSxcbiAgICAgIDIxOSxcbiAgICAgIDcwLFxuICAgICAgMjI5LFxuICAgICAgMzYsXG4gICAgICA5LFxuICAgICAgMTQ3LFxuICAgICAgMTcsXG4gICAgICAxMTgsXG4gICAgICAyNTEsXG4gICAgICAxOTksXG4gICAgICA5MFxuICAgIF1cbiAgfSxcbiAgXCJyZWdpc3RlcmVkXCI6IHRydWUsXG4gIFwiYmFja3VwVG9rZW5cIjoge1xuICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgIFwiZGF0YVwiOiBbXG4gICAgICAyNDgsXG4gICAgICA2NixcbiAgICAgIDE5MixcbiAgICAgIDEzNCxcbiAgICAgIDEyNCxcbiAgICAgIDIwNixcbiAgICAgIDUzLFxuICAgICAgMjUzLFxuICAgICAgMTA1LFxuICAgICAgMTk2LFxuICAgICAgMzgsXG4gICAgICAxMjEsXG4gICAgICAzMyxcbiAgICAgIDI0OCxcbiAgICAgIDIxMixcbiAgICAgIDExMixcbiAgICAgIDE4OCxcbiAgICAgIDQwLFxuICAgICAgMTgwLFxuICAgICAgMjA2XG4gICAgXVxuICB9LFxuICBcInJlZ2lzdHJhdGlvblwiOiB7fSxcbiAgXCJwYWlyaW5nQ29kZVwiOiBcIjI3NFdTTUQ1XCIsXG4gIFwibWVcIjoge1xuICAgIFwiaWRcIjogXCIyMzc2Nzk2NzIxMDc6NTRAcy53aGF0c2FwcC5uZXRcIixcbiAgICBcIm5hbWVcIjogXCJQZXRlciBlc3Nva2FeX15cIixcbiAgICBcImxpZFwiOiBcIjk1MDM1MDc2OTM5OTgxOjU0QGxpZFwiXG4gIH0sXG4gIFwiYWNjb3VudFwiOiB7XG4gICAgXCJkZXRhaWxzXCI6IFwiQ0wzU3FhOEJFUFdkK2JRR0dCMGdBQ2dBXCIsXG4gICAgXCJhY2NvdW50U2lnbmF0dXJlS2V5XCI6IFwiUmRZckJKMDMyRGVvTWlVbUFEWDFwNmMxS2pIWVZiNkxoTzhsSTJTd0pBUT1cIixcbiAgICBcImFjY291bnRTaWduYXR1cmVcIjogXCJWTjBpZlV4dUtLMzZpL1ZGZXlwamxOelJoQ1hycVRKRFROSkQrT3poZWx3aHBoNGk2M3Nudjk3T1JuL2ZaTUNqY1hOWjNPQ2JCSU9wdWs4Qlk5dEhEZz09XCIsXG4gICAgXCJkZXZpY2VTaWduYXR1cmVcIjogXCIxWFNOSnhodXQ0S1QvTEEyK1lYUW5sT244WHNySGRFVmdTVHk1TWdoZ1dBZWJzcGJWWXNrMWo0b0kwQWhnRlNuV3RnQSt4QW8vSmk1Q0JoRG5JcmlpQT09XCJcbiAgfSxcbiAgXCJzaWduYWxJZGVudGl0aWVzXCI6IFtcbiAgICB7XG4gICAgICBcImlkZW50aWZpZXJcIjoge1xuICAgICAgICBcIm5hbWVcIjogXCIyMzc2Nzk2NzIxMDc6NTRAcy53aGF0c2FwcC5uZXRcIixcbiAgICAgICAgXCJkZXZpY2VJZFwiOiAwXG4gICAgICB9LFxuICAgICAgXCJpZGVudGlmaWVyS2V5XCI6IHtcbiAgICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgICAgNSxcbiAgICAgICAgICA2OSxcbiAgICAgICAgICAyMTQsXG4gICAgICAgICAgNDMsXG4gICAgICAgICAgNCxcbiAgICAgICAgICAxNTcsXG4gICAgICAgICAgNTUsXG4gICAgICAgICAgMjE2LFxuICAgICAgICAgIDU1LFxuICAgICAgICAgIDE2OCxcbiAgICAgICAgICA1MCxcbiAgICAgICAgICAzNyxcbiAgICAgICAgICAzOCxcbiAgICAgICAgICAwLFxuICAgICAgICAgIDUzLFxuICAgICAgICAgIDI0NSxcbiAgICAgICAgICAxNjcsXG4gICAgICAgICAgMTY3LFxuICAgICAgICAgIDUzLFxuICAgICAgICAgIDQyLFxuICAgICAgICAgIDQ5LFxuICAgICAgICAgIDIxNixcbiAgICAgICAgICA4NSxcbiAgICAgICAgICAxOTAsXG4gICAgICAgICAgMTM5LFxuICAgICAgICAgIDEzMixcbiAgICAgICAgICAyMzksXG4gICAgICAgICAgMzcsXG4gICAgICAgICAgMzUsXG4gICAgICAgICAgMTAwLFxuICAgICAgICAgIDE3NixcbiAgICAgICAgICAzNixcbiAgICAgICAgICA0XG4gICAgICAgIF1cbiAgICAgIH1cbiAgICB9XG4gIF0sXG4gIFwicGxhdGZvcm1cIjogXCJzbWJhXCIsXG4gIFwibGFzdEFjY291bnRTeW5jVGltZXN0YW1wXCI6IDE3MjE2NTA5MzgsXG4gIFwibXlBcHBTdGF0ZUtleUlkXCI6IFwiQUFBQUFNbjVcIlxufSIsCiAgImFwcC1zdGF0ZS1zeW5jLWtleS1BQUFBQU1uNS5qc29uIjogIntcImtleURhdGFcIjpcInA4SXhEeVdraEd2MDJ0UHl2U0tFTjgzZFpsZDRQaU5GQmxPdVM1THU2WjQ9XCIsXCJmaW5nZXJwcmludFwiOntcInJhd0lkXCI6MzY3NjgzOTAwLFwiY3VycmVudEluZGV4XCI6MzAsXCJkZXZpY2VJbmRleGVzXCI6WzAsMjgsMzBdfSxcInRpbWVzdGFtcFwiOlwiMTcxODE3ODI0MzY2NFwifSIKfQ==

 process.env.SESSION_ID ||  "SUHAIL_12_22_07_22_ewogICJjcmVkcy5qc29uIjogIntcbiAgXCJub2lzZUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTkyLFxuICAgICAgICAyLFxuICAgICAgICA1OSxcbiAgICAgICAgMjIwLFxuICAgICAgICAxMyxcbiAgICAgICAgNDEsXG4gICAgICAgIDI0OCxcbiAgICAgICAgMjM0LFxuICAgICAgICAxMCxcbiAgICAgICAgMjcsXG4gICAgICAgIDE5NixcbiAgICAgICAgMjQxLFxuICAgICAgICA2LFxuICAgICAgICAxMDksXG4gICAgICAgIDkzLFxuICAgICAgICAyMDgsXG4gICAgICAgIDE2NixcbiAgICAgICAgMTc4LFxuICAgICAgICAyMjEsXG4gICAgICAgIDIxOSxcbiAgICAgICAgMjEyLFxuICAgICAgICAyNDcsXG4gICAgICAgIDE0OSxcbiAgICAgICAgMjU1LFxuICAgICAgICAyNTMsXG4gICAgICAgIDQ2LFxuICAgICAgICA1MyxcbiAgICAgICAgMjA5LFxuICAgICAgICA4LFxuICAgICAgICAxNjAsXG4gICAgICAgIDEzMixcbiAgICAgICAgMTE4XG4gICAgICBdXG4gICAgfSxcbiAgICBcInB1YmxpY1wiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDc0LFxuICAgICAgICAxMzYsXG4gICAgICAgIDE0OSxcbiAgICAgICAgMjUyLFxuICAgICAgICAyMDEsXG4gICAgICAgIDE3MSxcbiAgICAgICAgMTkyLFxuICAgICAgICAxOSxcbiAgICAgICAgMTIsXG4gICAgICAgIDQwLFxuICAgICAgICA0NSxcbiAgICAgICAgMTQ1LFxuICAgICAgICAyMzAsXG4gICAgICAgIDM0LFxuICAgICAgICA0MyxcbiAgICAgICAgMTgzLFxuICAgICAgICAxNDgsXG4gICAgICAgIDQxLFxuICAgICAgICA1MCxcbiAgICAgICAgMTcsXG4gICAgICAgIDE2OSxcbiAgICAgICAgMjQ3LFxuICAgICAgICAxODcsXG4gICAgICAgIDIzNyxcbiAgICAgICAgMTY1LFxuICAgICAgICAxNDksXG4gICAgICAgIDE1MyxcbiAgICAgICAgMTE0LFxuICAgICAgICAxNjAsXG4gICAgICAgIDExNCxcbiAgICAgICAgMTA0LFxuICAgICAgICA3OFxuICAgICAgXVxuICAgIH1cbiAgfSxcbiAgXCJwYWlyaW5nRXBoZW1lcmFsS2V5UGFpclwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMjQ4LFxuICAgICAgICAzOCxcbiAgICAgICAgOTcsXG4gICAgICAgIDE0NyxcbiAgICAgICAgNDIsXG4gICAgICAgIDE2MixcbiAgICAgICAgNzUsXG4gICAgICAgIDgzLFxuICAgICAgICAxNTMsXG4gICAgICAgIDEzOCxcbiAgICAgICAgMTgyLFxuICAgICAgICAxNjMsXG4gICAgICAgIDQ1LFxuICAgICAgICAxODIsXG4gICAgICAgIDEyMCxcbiAgICAgICAgMjQ2LFxuICAgICAgICAyMTgsXG4gICAgICAgIDE4MyxcbiAgICAgICAgMTU1LFxuICAgICAgICAyNTMsXG4gICAgICAgIDE0OSxcbiAgICAgICAgMTQsXG4gICAgICAgIDI0NixcbiAgICAgICAgMTUsXG4gICAgICAgIDExMSxcbiAgICAgICAgMjUzLFxuICAgICAgICAyNDEsXG4gICAgICAgIDExNCxcbiAgICAgICAgMTYyLFxuICAgICAgICA2LFxuICAgICAgICAyMzgsXG4gICAgICAgIDY3XG4gICAgICBdXG4gICAgfSxcbiAgICBcInB1YmxpY1wiOiB7XG4gICAgICBcInR5cG


module.exports = {

  menu: process.env.MENU || "", /**  Available @MENU @Schemes 1: Aztec_Md, 2: A17_Md, 3: Suhail-Md Default ---------- If Not Choose then it Randomely Pic One Of Them Each time **/

  HANDLERS: process.env.PREFIX  || ":",
  BRANCH  : process.env.BRANCH  || "main",
  VERSION : process.env.VERSION || "1.3.8",
  caption : global.caption || "" , // ```『 ᴘᴏᴡᴇʀᴇᴅ ʙʏ sᴜʜᴀɪʟ²²¹-ᴍᴅ 』```", //*『sᴜʙsᴄʀɪʙᴇ • sᴜʜᴀɪʟ ᴛᴇᴄʜ』*\n youtube.com/@suhailtechinfo0"),
 
  author : process.env.PACK_AUTHER|| "",
  packname: process.env.PACK_NAME || "",
  botname : process.env.BOT_NAME  || "sᴜʜᴀɪʟ-ᴍᴅ",
  ownername:process.env.OWNER_NAME|| "peter"


  errorChat : process.env.ERROR_CHAT || "",
  KOYEB_API : process.env.KOYEB_API  || "false",

  REMOVE_BG_KEY : process.env.REMOVE_BG_KEY  || "",
  OPENAI_API_KEY: process.env.OPENAI_API_KEY || "",
  HEROKU_API_KEY: process.env.HEROKU_API_KEY || "",
  HEROKU_APP_NAME:process.env.HEROKU_APP_NAME|| "",
  antilink_values:process.env.ANTILINK_VALUES|| "all",
  HEROKU: process.env.HEROKU_APP_NAME && process.env.HEROKU_API_KEY,


  WORKTYPE: process.env.WORKTYPE || process.env.MODE|| "private",
  LANG: ( process.env.THEME ||  "SUHAIL"  ).toUpperCase(),



};



global.ELEVENLAB_API_KEY = process.env.ELEVENLAB_API_KEY || "";
global.aitts_Voice_Id = process.env.AITTS_ID|| "37";





















global.rank = "updated"
global.isMongodb = false; 
let file = require.resolve(__filename)
fs.watchFile(file, () => { fs.unwatchFile(file);console.log(`Update'${__filename}'`);delete require.cache[file];	require(file); })
 

// ========================= [ Disables in V.1.2.8 ] ===============================\\  
  //style : process.env.STYLE || "2",  // put '1' & "2" here to check bot styles
  //readmessage:process.env.READ_MESSAGE|| "false",
  //warncount: process.env.WARN_COUNT || 3,
  //userImages:process.env.USER_IMAGES|| "text",  // SET IMAGE AND VIDEO URL FOR BOT MENUS 
  //disablepm: process.env.DISABLE_PM || "false",
  //MsgsInLog: process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
  //readcmds:process.env.READ_COMMANDS|| "false", 
  //alwaysonline:process.env.WAPRESENCE|| "unavailable", // 'unavailable' | 'online' | 'composing' | 'recording' | 'paused'
  //read_status: process.env.AUTO_READ_STATUS || "false",
  //save_status: process.env.AUTO_SAVE_STATUS || "false",
  //aitts_Voice_Id : process.env.AITTS_ID || "37",
  //ELEVENLAB_API_KEY: process.env.ELEVENLAB_API_KEY  || "",
